//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_test_week.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userstbl
    {
        public string username { get; set; }
        public string password { get; set; }
        public string country { get; set; }
        public string complete_name { get; set; }
    }
}
